name: scrollable_text_indicator
description: A Flutter package that provides a scrollable text with vertical indicator.
version: 0.0.1
homepage: https://github.com/SlavisDEV/scrollable_text_indicator

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

